go

diff --git a/.github/workflows/policies.yml b/.github/workflows/policies.yml
--- a/.github/workflows/policies.yml
+++ b/.github/workflows/policies.yml
@@ -47,17 +47,18 @@ jobs:
           enable-AzPSSession: true
 
       - name: Compare policies, initiatives, and assignments
+        id: compare-policies
         uses: azure/powershell@v1
         with:
           inlineScript: |
-            $pr = $${{ github.event_name == 'pull_request' }}
-            ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/scripts/Compare-Policy.ps1 -Path "${{ github.workspace }}/modules/${{ env.MODULE_NAME }}" -ManagementGroupRoot ${{ env.MANAGEMENT_GROUP_ROOT }} -Verbose
-            Write-Host "pr: $pr"
-            Write-Host "deleted: $script:deleteDetected"
-            if ($pr -and $script:deleteDetected) {
-              Write-Error "Delete detected. Manual intervention required."
-            }
+            ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/scripts/Compare-Policy.ps1 -Path "${{ github.workspace }}/modules/${{ env.MODULE_NAME }}" -ManagementGroupRoot ${{ env.MANAGEMENT_GROUP_ROOT }}
           azPSVersion: latest
+
+      - name: Fail on delete detected if build reason is pull request
+        run: |
+          echo "::error::Delete detected. Manual intervention required."
+          exit 1
+        if: steps.compare-policies.DELETE_DETECTED && github.event_name == 'pull_request'
 
       - name: What if deploy policies, initiatives, and assignments
         uses: azure/powershell@v1
@@ -86,17 +87,18 @@ jobs:
           enable-AzPSSession: true
 
       - name: Compare policies, initiatives, and assignments
+        id: compare-policies
         uses: azure/powershell@v1
         with:
           inlineScript: |
-            $main = $${{ github.ref == 'refs/heads/main' }}
-            ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/scripts/Compare-Policy.ps1 -Path "${{ github.workspace }}/modules/${{ env.MODULE_NAME }}" -ManagementGroupRoot ${{ env.MANAGEMENT_GROUP_ROOT }} -Verbose
-            Write-Host "MAIN: $main"
-            Write-Host "deleted: $script:deleteDetected"
-            if ($main -and $script:deleteDetected) {
-              Write-Error "Delete detected. Manual intervention required."
-            }
+            ${{ github.workspace }}/modules/${{ env.MODULE_NAME }}/scripts/Compare-Policy.ps1 -Path "${{ github.workspace }}/modules/${{ env.MODULE_NAME }}" -ManagementGroupRoot ${{ env.MANAGEMENT_GROUP_ROOT }}
           azPSVersion: latest
+
+      - name: Fail on delete detected if branch is main
+        run: |
+          echo "::error::Delete detected. Manual intervention required."
+          exit 1
+        if: steps.compare-policies.DELETE_DETECTED && github.ref == 'refs/heads/main'
 
       - name: What if deploy policies, initiatives, and assignments
         uses: azure/powershell@v1
